server:
    port: 8080

proindiemusic:
    client:
        clientId: 100000001-R8egtlt0Swr422zyYTM78NIPOFAsu03m76uz0eSRoFlPk.oauth2user.aabo.tech
        clientSecret: VCaosuWY4LO2C59vUuGlUyshhybqfZ
        accessTokenUri: https://proindiemusic-oauth.mybluemix.net/oauth2/token
        userAuthorizationUri: https://proindiemusic-oauth.mybluemix.net/oauth2/auth
        clientAuthenticationScheme: form
    resource:
        userInfoUri: https://proindiemusic-oauth.mybluemix.net/oauth2/user