server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://sl-us-south-1-portal.53.dblayer.com:17879/oauth2
    username: admin
    password: VDQGIAWFJENCYCVG
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 50
      test-on-borrow: true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-test-query: SELECT 1
      maxLifetime: 1800000
      isolate-internal-queries: true